### ISSUE TITLE
Recompile to make compatible with 9.0.0

### ISSUE THREAD

**Issue by cucholix** [SunTheCourier/sys-clk-Editor#10]
Apps needs to be recompiled against the new libnx or else they won’t be able to detect button inputs, atmosphere will still give support for old libnx, but eventually it will be dropped in the future.

More info: https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by gabehxd** [comment]
Already done

**Comment by gabehxd** [comment]
wait sorry my bad mixing it up with a different homebrew

**Comment by hippydave** [comment]
[sys-clk-Editor.nro.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3639990/sys-clk-Editor.nro.zip)
Just built from master, for anyone who needs it in the meantime. Tested working with 9.0.0.
Tho if you don't trust random binaries, build it yourself.

**Comment by gabehxd** [comment]
Once i finished with refactoring i will make a new release
