### ISSUE TITLE
Sys-clk-Editor won't start

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [SunTheCourier/sys-clk-Editor#11]
Firmware 8.1.0
Atmosphere 0.9.4
Sys-clk is enabled

Tried latest Homebrew Menu in Applet Mode and regular mode.
Whenever i try to start sys-clk-editor it boots me back into the homebrew menu.
The screen blinks to black for about two seconds and i am back in the homebrew menu.

**Comment by gabehxd** [comment]
have not been able to reproduce issue

**Comment by VorgonBattlecruiser** [comment]
Any way for me to help?
Found another person on reddit from yesterday who seemed to have the same issue.

**Comment by gabehxd** [comment]
could you try to make sure config files are in the right place

**Comment by gabehxd** [comment]
please also make sure your system is on fat32

**Comment by VorgonBattlecruiser** [comment]
System is fat32
background services: sys-clk and ftp
my config is located in: \config\sys-clk\config.ini

attached my config.ini (renamed to .txt, it wont allow uploading ini files)
[config.txt](https://github.com/SunTheCourier/sys-clk-Editor/files/3621879/config.txt)

**Comment by Avrution** [comment]
At least I'm not alone in this.  

I did a test where I copied my setup to the emunand and then wiped it - everything worked.  This helped me rule out the cfw files and sd card.

Do you happen to have more than one user or had one and have since deleted it using devmenu?

**Comment by VorgonBattlecruiser** [comment]
No, only ever had one user on my Switch.
Also glad to know that i am not the only one.
If more people used the tool and reported back we may eventually get to the bottom of this.

**Comment by gabehxd** [comment]
I have a feeling it has to do with emummc. Both of you have it right?

**Comment by Avrution** [comment]
Sysnand only - emu was just a test so as to not wipe out my actual system

**Comment by VorgonBattlecruiser** [comment]
Same, Sysnand CFW.

**Comment by gabehxd** [comment]
Could you try overriding a game and tell me if an error is thrown somewhere

**Comment by VorgonBattlecruiser** [comment]
I just tried again. Just a black screen for a second or two and then i am back in the homebrew menu.

**Comment by gabehxd** [comment]
Do you have any pirated games or homebrew installed to the system as in on the home menu

**Comment by VorgonBattlecruiser** [comment]
Yes, games on the home-screen, homebrew only via the homebrew menu. None of those installed as NSP.

**Comment by gabehxd** [comment]
I still have no idea of the cause but i will try making some modifications and have a patch for you guys to test

**Comment by VorgonBattlecruiser** [comment]
I am also really confused. If i could think of some unusual stuff i had done with my switch, i would tell you.
But i basically just use it for gaming and homebrew-stuff.
No themes, no changes to the system itself, no emunand.

Is it maybe something me and Avrution have installed, and others may not, that could be the issue?
Is there a way to create a list of all installed title-ids so we could check what me and Avrution have in common?

**Comment by Avrution** [comment]
Is it possible to enable any kind of logging, similar to how the actual sys-clk uses the flag file to create a log?  Maybe we could see what/where the failure point it.

**Comment by gabehxd** [comment]
Like i said ill make some modifications (to add logging) and we can go from there

**Comment by gabehxd** [comment]
Sorry for the wait but i got some code cleaned up and logging done. Please send back the log file from this NRO 
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3638059/sys-clk-Editor.zip)

**Comment by Avrution** [comment]
Unless the log file is put into another folder, nothing is created for me.  Tried in both applet mode and regular.

**Comment by gabehxd** [comment]
my bad try making `editor-debug.log` at root

**Comment by Avrution** [comment]
Still nothing

**Comment by gabehxd** [comment]
what does you SD look like

**Comment by Avrution** [comment]
In what way?

**Comment by gabehxd** [comment]
what does the root look like

**Comment by Avrution** [comment]
build.zip
editor-debug.log
hbmenu.nro
hddinst.log

**Comment by gabehxd** [comment]
the *root* of the SD not the switch folder(?)

**Comment by Avrution** [comment]
Yes, excluding all of the folders, unless you would like them as well

**Comment by gabehxd** [comment]
list everything

**Comment by Avrution** [comment]
atmosphere
backup
bootloader
config
EdiZon
emuiibo
ftpd
goldleaf
Install
JKSV
Nintendo
sept
switch
System Volume Information
themes
tinfoil
Toolkit
build.zip
editor-debug.log
hbmenu.nro
hddinst.log

**Comment by gabehxd** [comment]
try this last NRO
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3638268/sys-clk-Editor.zip)

**Comment by Avrution** [comment]
No change

**Comment by gabehxd** [comment]
This should do something
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3638279/sys-clk-Editor.zip)

**Comment by Avrution** [comment]
Program actually opens and logging works

**Comment by gabehxd** [comment]
what the fuck

**Comment by gabehxd** [comment]
could you provide me the log

**Comment by SunTheCourier** [comment]
could you dispose of the timer you have introduced?

**Comment by Avrution** [comment]
So far it only says:

menu has been written!

I will test it more a little later

**Comment by gabehxd** [comment]
what happens trying to open the games menu

**Comment by Avrution** [comment]
I guess it only logs whatever is done last.  I changed a few options and when I exited the log only said

Exit!

I can open the menu and change options just fine.  Changes stick between uses.

Is there a way to sort by name versus whatever this default is?

**Comment by gabehxd** [comment]
no it sorts by whatever app was used last afaik

**Comment by gabehxd** [comment]
and i will fix the log right now

**Comment by Avrution** [comment]
Seems to sort by whatever was last updated.  My top apps I have never run before, but installed updates for.

**Comment by gabehxd** [comment]
this should fix logging
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3638286/sys-clk-Editor.zip)

**Comment by gabehxd** [comment]
bumping for a log ^^

**Comment by Avrution** [comment]
Entering main loop!
menu has been written!
Case -69
Exit!

**Comment by gabehxd** [comment]
there should be more than that

**Comment by gabehxd** [comment]
make sure you do not delete ever only delete the contents of it if you want!

**Comment by Avrution** [comment]
That is all it writes.  Tried again with the same results and even cleared out the file first.

**Comment by gabehxd** [comment]
Please try this build.
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3639419/sys-clk-Editor.zip)

**Comment by Avrution** [comment]
Attached

**Comment by Avrution** [comment]
Let's try this again

[editor-debug.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/3639463/editor-debug.zip)

**Comment by gabehxd** [comment]
Having known you had pirated/homebrew titles would have helped :\ but i think i found the issue. A title with TID `0100b1400cd50000` which is `Atelier Lulua ~The Scion of Arland~` according to NSWDB was not installed properly and the data which contained it's name was not found and caused it to break the program.

**Comment by gabehxd** [comment]
to be specific `nsGetApplicationControlData` failed
