### ISSUE TITLE
Sys-Clk-Editor will not switch from disabled to enabled in latest release.

### ISSUE THREAD

**Issue by beefsloth** [SunTheCourier/sys-clk-Editor#16]
9.1.0 and updated to 10.1 atmosphere. When I try to enable sys-clk-editor it wont changed from disabled. Logging will change to enabled like it's supposed too. I'm using latest update 1.3. Do I need to place a config file somewhere or does it do it itself like when installed from the hb store?

**Comment by gabehxd** [comment]
can try updating atmosphere there was a silent fix for a specific bug that affected some services

**Comment by gabehxd** [comment]
pinging @beefsloth

**Comment by gabehxd** [comment]
closing as it is inactive
