### ISSUE TITLE
"rror: 0x615ress '+' to exit"

### ISSUE THREAD

**Issue by IBNobody** [SunTheCourier/sys-clk-Editor#17]
I'm getting the following error when loading from applet mode and from redirect mode on Atmosphere 0.10.1 and FW 8.10:

"rror: 0x615ress '+' to exit"

sys-clk seems to be running fine according to the logs.

**Comment by gabehxd** [comment]
Make sure to update your Atmosphere version

**Comment by gabehxd** [comment]
And is the text written exactly how you quote it if so could you provide a screenshot?

**Comment by IBNobody** [comment]
I'm running the latest version of Atmosphere...

![image](https://user-images.githubusercontent.com/5863888/70857149-180f7e00-1eaf-11ea-830c-66fda6b42b9f.png)

And yes, the exact red text is "rror: 0x615ress '+' to exit!" 

![image](https://user-images.githubusercontent.com/5863888/70857172-5311b180-1eaf-11ea-81ea-cdd320a0e560.png)

**Comment by gabehxd** [comment]
Atmosphere had a shadow fix a while a few days ago make sure to update it anyways

**Comment by IBNobody** [comment]
Thanks. That did it.
