### ISSUE TITLE
Don't work on Kosmos v15 - App Crash.

### ISSUE THREAD

**Issue by tabnk** [SunTheCourier/sys-clk-Editor#20]
On Kosmos v15 (https://github.com/AtlasNX/Kosmos/releases) with firmware 9.1.0

Cannot select a game title as it will crash the Sys Clk editor.

**Comment by gabehxd** [comment]
Can you make sure you on the latest version. If it persists please send a crash report

**Comment by tabnk** [comment]
I'm using this version https://github.com/SunTheCourier/sys-clk-Editor/releases/tag/v1.3.  

Where to get the crash report?

**Comment by tabnk** [comment]
Found the crash report folder. Will send it now.

**Comment by tabnk** [comment]
Attached crash report for sys-clk-Editor

[01577928983_0100c8e0083c4000.log](https://github.com/SunTheCourier/sys-clk-Editor/files/4014752/01577928983_0100c8e0083c4000.log)

**Comment by gabehxd** [comment]
[sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/4014765/sys-clk-Editor.zip)
can you try this build

**Comment by tabnk** [comment]
> [sys-clk-Editor.zip](https://github.com/SunTheCourier/sys-clk-Editor/files/4014765/sys-clk-Editor.zip)
> can you try this build

Tried. No crash but cannot overclock. PPSSPP still run at stock clock.

**Comment by gabehxd** [comment]
did you enable sys clk/how can you tell PPSSPP is running in stock

**Comment by tabnk** [comment]
Yes, it is enabled. On PPSSPP **before** using sys clk editor Tekken 6 will run about 45-53 fps but **after** sys clk editor still the same fps.

**Comment by gabehxd** [comment]
can you check the configuration

**Comment by tabnk** [comment]
Config/sys-clk/config.ini look fine.

**Comment by gabehxd** [comment]
then the clock issue should be on your side. Make sure you set the correct application to overclock

**Comment by tabnk** [comment]
Overclock Game, load game (R Button), homebrew-> PPSSPP. Is it correct?

**Comment by gabehxd** [comment]
yes, make sure it also works manually
