### ISSUE TITLE
sys-clk was not found!

### ISSUE THREAD

**Issue by supdotcom** [SunTheCourier/sys-clk-Editor#26]
Hi I'm getting an error with the sys clk editor where when I load in it shows "sys-clk was not found!".

9.1.0 w/ 0.10.4 atmosphere

**Comment by gabehxd** [comment]
It most likely means you didn't not install sys clk (properly)

**Comment by supdotcom** [comment]
From sys clk I copied the atmosphere folder and the config folder into the sdcard root, as per the instructions.

**Comment by gabehxd** [comment]
make sure your using the latest versions of software

**Comment by supdotcom** [comment]
solved it by putting sys-clk in atmosphere/contents instead of the default directory which copied sys-clk to atmosphere/title.
