### ISSUE TITLE
Clock table description (enhancement)

### ISSUE THREAD

**Issue by HakimEG** [SunTheCourier/sys-clk-Editor#8]
Works pretty darn well, thanks for the work!

One thing i found that would be a nice addition, is the clock table description.

It's a good reference to know which is the standard docked/handheld cpu/gpu/mem freq and such directly in the table :) 

It's already written out here https://github.com/retronx-team/sys-clk#clock-table-mhz

**Comment by gabehxd** [comment]
Already started work on this!

**Comment by gabehxd** [comment]
Done
